### ISSUE TITLE
Monitor wrapper

### ISSUE THREAD

**Issue by weepingwillowben** [PettingZoo-Team/SuperSuit#17]
[Gyms monitor wrapper](https://github.com/openai/gym/blob/master/gym/wrappers/monitor.py) allows you to collect data on a trained agent during or after training easily. 

Is this a feature supersuit needs to have?

**Comment by justinkterry** [comment]
After internal discussion, the answer seems to be "no."

**Comment by Simon-Fuhaoyuan** [comment]
So how can I plot the RL pictures after training without Monitor wrapper?
