### ISSUE TITLE
Preprocessing order for graphical environments

### ISSUE THREAD

**Issue by yutaizhou** [PettingZoo-Team/SuperSuit#32]
Hi! More of a usage/best practice question than pkg issue. I am using Knight Archer Zombies as an env to train MARL algorithms in RLlib. because KAZ is a graphical env, I have to preprocess it to work with RLlib's default conv filter size (512x512x3 -> 84x84xK). 

I am using the following wrappers: 

- color reduction
- frame stack
- resize
- dtype
- normalize

Is there a heuristic for determining the order in which these should be applied?
Of which resize is

**Comment by justinkterry** [comment]
> because KAZ is a graphical env, I have to preprocess it to work with RLlib's default conv filter size (512x512x3 -> 84x84xK).
You could also change RLlibs CNN too

I mean there's not a hard heuristic I'm aware of, just think through what wrappers you're applying and what order it makes the most sense to do things in. The only thing you're doing wrong in that order that I can see is that it should be appreciably faster to do frame stacking after resize instead of before.

**Comment by justinkterry** [comment]
Moving normalize around may also have meaningful performance impacts, but that's something that would have to be experimentally tested.

In terms of doing things "wrong" more than slower, like I said it's going to come down to thinking through what different things are doing. One big one for that is not using frame stacking before agent indicator

**Comment by weepingwillowben** [comment]
So in my performance tests, frame_stack is the slowest operation. So I recommend performing resize() before frame_stack, to reduce the amount of work it has to do.

**Comment by yutaizhou** [comment]
Thanks for the help! Is there a help forum just supersuit and pettingzoo? With AAMAS deadline looming, I am sure there would be a lot more questions.

**Comment by weepingwillowben** [comment]
This github issues page is all we have for now. Is there some other format you suggest?

**Comment by yutaizhou** [comment]
Perhaps a slack or discourse? The idea is to keep issues (GitHub) and use cases/specific scenarios separate

**Comment by justinkterry** [comment]
In general I'd say that's a bad idea, but you guys at lincoln lab are using pettingzoo so heavily that maybe we should have a joint slack or something? Also if you have a minute some time, I'd love to know more about the landscape of what all your guys are using pettingzoo for.

**Comment by justinkterry** [comment]
Also we have a legitimate citation for pettingzoo now if you're using it for an aamas submission (its in the main readme)
