### ISSUE TITLE
Crop observation wrapper

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/SuperSuit#50]
At some point, it would be a good idea to have a wrapper that can crop the observation space

**Comment by weepingwillowben** [comment]
I mean, if the environment produces an observation outside of the space, it is a bug. If you want to make a hack to support a buggy environment, I would encourage people to use the observation lambda wrapper, which can easily support this case.

**Comment by AzOuss96** [comment]
I think it would be interesting to have a wrapper that crops observations, which can be useful in the case of learning in partial observability.

**Comment by benblack769** [comment]
If you want to do this now, I would familiarize yourself with the observation lambda function: https://github.com/PettingZoo-Team/SuperSuit#lambda-functions

If you have a specific idea of how the crop_observation wrapper should be parameterized (how do you described what should be cropped) and a specific use case where using a wrapper offers benefits over modifying the environment, then I would consider full support for such a wrapper.
