### ISSUE TITLE
Supersuit should have atari documentation as an example

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/SuperSuit#53]
Basically, this example should probably be in the supersuit docs as well:

https://github.com/PettingZoo-Team/PettingZoo/blob/master/docs/atari.md#preprocessing

**Comment by justinkterry** [comment]
1) knock yourself out
2) you're supposed to be working on parameter sharing

**Comment by justinkterry** [comment]
@weepingwillowben can this be done or closed?

**Comment by justinkterry** [comment]
@weepingwillowben can this be closed?
