### ISSUE TITLE
action_lambda_v0 could not change gym env's action_space

### ISSUE THREAD

**Issue by susumuota** [PettingZoo-Team/SuperSuit#62]
I suppose this should be `self.action_space` not `self.action_spaces` in gym_wrapper.py

https://github.com/PettingZoo-Team/SuperSuit/blob/242dc51ca72d94a0930c431a4d0d1c7279f362d2/supersuit/gym_wrappers.py#L228

I tried to change Pong's action_space but could not change.
```
env = gym.make('PongNoFrameskip-v4')
print(env.action_space)  # Discrete(6)
# print(env.action_spaces)  # error. it's OK.
env = action_lambda_v0(env,
    lambda action, space: action,
    lambda space: gym.spaces.Discrete(3))
print(env.action_space)  # should be Discrete(3) but got Discrete(6)
print(env.action_spaces) # should be error but got Discrete(3)
```

**Comment by justinkterry** [comment]
@weepingwillowben

**Comment by weepingwillowben** [comment]
Thanks for reporting this rather embarrassing bug. A fix for this bug and a test to make sure it won't happen again is in PR #63.

P.S. I'm glad you find the action_lambda wrapper useful. In my opinion, the lambda wrappers are really one of the more interesting and unique features of supersuit.

**Comment by susumuota** [comment]
Thank you for fixing!

> P.S. I'm glad you find the action_lambda wrapper useful. In my opinion, the lambda wrappers are really one of the more interesting and unique features of supersuit.

Yes, it looks very smart and clean way to modify environment.

I think PettingZoo/SuperSuit are very useful and important standardization. Thank you and your team for developing them. Keep on going!
