### ISSUE TITLE
Rename "Depreciated"

### ISSUE THREAD

**Issue by RyanNavillus** [PettingZoo-Team/SuperSuit#67]
It looks like when we fixed this we left one instance unchanged. I'm leaving this because I don't know if it requires a version bump. https://github.com/PettingZoo-Team/SuperSuit/blob/60d1715f7a41b7e542a1ff41a629ab4b9432394b/supersuit/__init__.py#L48

**Comment by weepingwillowben** [comment]
This was fixed in pettingzoo, but there is similar, independent functionality in SuperSuit
