### ISSUE TITLE
KeyError: 'terminal_observation'

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/SuperSuit#72]
```
  File "/home/anni/miniconda3/envs/tf15/lib/python3.7/site-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 54, in step_wait
    infos[idx]["terminal_observation"] = self.transpose_image(infos[idx]["terminal_observation"])
KeyError: 'terminal_observation'
```

script that I ran:

```
from stable_baselines3 import PPO
from pettingzoo.atari import pong_v1 as pistonball_v4
import supersuit as ss
env = pistonball_v4.parallel_env()
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 8, num_cpus=4, base_class='stable_baselines3')
model = PPO('CnnPolicy', env, verbose=3, n_steps=1028)
model.learn(total_timesteps=20000000)
model.save('policy_3')
```

**Comment by justinkterry** [comment]
So if you downgrade to stable_baselines 2 this works for now. I just encountered this myself with SB3.

@weepingwillowben can you please fix this this weekend?

**Comment by weepingwillowben** [comment]
I can't seem to reproduce this error with the latest versions of supersuit and SB3. Which versions are you running?

**Comment by justinkterry** [comment]
justinkterry@prophet:~$ pip3 freeze
absl-py==0.9.0
aiohttp==3.6.2
array2gif==1.0.4
asn1crypto==0.24.0
astor==0.8.1
async-timeout==3.0.1
atari-py==0.2.6
attrs==17.4.0
Automat==0.6.0
autonomous-learning-library==0.6.2
beautifulsoup4==4.9.0
blinker==1.4
box2d-py==2.3.8
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==6.7
cloud-init==20.4
cloudpickle==1.6.0
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
Cython==0.29.21
distro-info===0.18ubuntu0.18.04.1
dm-tree==0.1.5
fail2ban==0.10.2
filelock==3.0.12
future==0.18.2
gallery-dl==1.16.5
gast==0.3.3
glfw==2.0.0
google==2.0.3
google-pasta==0.2.0
grpcio==1.28.1
gym==0.18.0
h5py==2.10.0
httplib2==0.9.2
hyperlink==17.3.1
idna==2.10
idna-ssl==1.1.0
imageio==2.9.0
importlib-metadata==1.6.0
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
language-selector==0.1
lockfile==0.12.2
lz4==3.0.2
Markdown==3.2.2
MarkupSafe==1.0
matplotlib==3.2.1
msgpack==0.6.2
mujoco-py==1.50.1.68
multidict==4.7.5
netifaces==0.10.4
numpy==1.19.5
oauthlib==2.0.6
opencv-python==4.2.0.34
opencv-python-headless==4.2.0.34
PAM==0.4.2
pandas==1.0.3
PettingZoo==1.6.1
Pillow==8.1.0
protobuf==3.11.3
py-spy==0.3.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.20
pycrypto==2.6.1
pygame==2.0.0
pyglet==1.5.0
pygobject==3.26.1
pyinotify==0.9.6
PyJWT==1.5.3
pymunk==6.0.0
pyOpenSSL==17.5.0
pyparsing==2.4.7
pyserial==3.4
python-apt==1.6.5+ubuntu0.5
python-dateutil==2.8.1
python-debian==0.1.32
pytz==2020.1
pyxdg==0.25
PyYAML==3.12
ray==0.8.5
redis==3.4.1
requests==2.25.1
requests-unixsocket==0.1.5
scipy==1.5.4
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
service-identity==16.0.0
six==1.11.0
soupsieve==2.0
speedtest-cli==2.0.0
ssh-import-id==5.7
stable-baselines3==1.0
SuperSuit==2.6.1
systemd-python==234
tabulate==0.8.7
tensorboard==1.14.0
tensorboardX==2.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
torch==1.5.1
torchvision==0.6.1
Twisted==17.9.0
typing-extensions==3.7.4.2
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.3
Werkzeug==1.0.1
wrapt==1.12.1
xkit==0.0.0
yarl==1.4.2
zipp==3.1.0
zope.interface==4.3.2

**Comment by weepingwillowben** [comment]
Ok, I reproduced it using the 13_lines.py. Don't know why the minimal example didn't trigger it. I'll get to fixing it

**Comment by weepingwillowben** [comment]
This has been fixed and released.
