### ISSUE TITLE
parameter sharing with variable number of agents + dictionaries

### ISSUE THREAD

**Issue by p-veloso** [PettingZoo-Team/SuperSuit#74]
Hi everyone, 
First of all, congrats for the library... it seems to be a simple and powerful approach to MARL.

**Question 1**
I am developing some parallel environments where the agents share the policy network. Each agent has the same action and observation space, but the number of agents can change when you reset the environment. Therefore, I had to use the black_death wrapper to train. 

```
env = MyParallelEnvironment(*args)
env = ss.black_death_v1(env)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 8, num_cpus=1, base_class='stable_baselines3')
model = PPO(MlpPolicy, env, verbose=3, gamma=0.99, n_steps=1000, ent_coef=0.01, learning_rate=0.00025, vf_coef=0.5, max_grad_norm=0.5, gae_lambda=0.95, n_epochs=4, clip_range=0.2, clip_range_vf=1)
model.learn(total_timesteps=2000000)
model.save("my_policy")

```
However, I am not sure if this is the most efficient way of training in this setting, once the required black_death wrapper creates many placeholders for the observations and (I assume) it passes additional tensors to the batches. Is there a better way to address this issue with SuperSuit?

**Question 2**
When I run the environment, the black_death wrapper is not necessary anymore. However, there is another problem. I have to convert the dictionary of observations into an array for the policy network. Then, I have to convert the resulting array  of actions into a dictionary for the parallel environment. I know that this dictionary is useful for other settings of multi agent systems, but is there a way to only work with arrays in SuperSuit?

```
env = MyParallelEnvironment(*args)
def dict_to_array(obs):
    a = []
    for i in range(len(obs.keys())):
        o = obs["bubble_" + str(i)]
        o = o.flatten()
        print(o.shape)
        a.append(o)
    return np.array(a)

def array_to_dict(act):
    d = dict()
    array_act = act[0]
    for i in range(array_act.shape[0]):
        d["bubble_" + str(i)] = array_act[i]
    return d

model = PPO.load("my_policy")
counter = 0
obs = env.reset()
for agent in range(1000):
    obs = dict_to_array(obs)
    act = model.predict(obs)
    act = array_to_dict(act)
    obs, reward, done, info = env.step(act)
    env.render()
```

**Comment by p-veloso** [comment]
1. I am confused with the agent death then. In my environment there is no agent death, only the number of agents change when I reset the environment. From the neural network perspective, this is not problematic, as the number of agents will be integrated to the "batch" dimension of the data.  
2. I am curious if is there anyway to avoid using the dictionary to store and transfer agent data in the parallel environment. The reason I am asking this is because in my setting the environment produces an array of observations (which is what the policy networks need) and it reads an array of actions in the method step. Therefore, I am only using the dictionary to adapt my environment to the environment template of SuperSuit.

**Comment by justinkterry** [comment]
1) I misread your question sorry. That's a really creative use of black death, I hadn't actually thought of that. You still can't do this without do this without black death and SB though, because the SB logic doesn't support variable numbers of agents (and it doing so make defining batch sizes weird). Writing custom code could handle this easily though.

I'll defer the second question to Ben

**Comment by weepingwillowben** [comment]
Hi, I'm glad you found our library promising.

So for the first question, stable baselines expects a vector environment to have a fixed size, so the vector environment needs to have as many elements as the maximum number of agents your environment can ever have. However, it shouldn't need to have more than that. We can discuss a solution if your vector environment has more agents than is possible to have at any given time. 

As for the second question, unfortunately, generality comes at a cost. Like any general library, supersuit does have this fixed interface where it expects environments to accept and return dictionaries. 

However, I guess I didn't think that should be a big burden either on the code or for performance. Your functions can be reduced to one-liners (admittedly verbose ones)

```
def dict_to_array(obs):
    return np.array([obs["bubble_" + str(i)].flatten() for i in len(obs.keys())])

def array_to_dict(act):
    array_act = act[0]
    return {d["bubble_" + str(i)]: array_act[i] for i in range(array_act.shape[0])}
```
