### ISSUE TITLE
Stable baselines3 doesn't support vectorized env

### ISSUE THREAD

**Issue by Ann-eat-apple** [PettingZoo-Team/SuperSuit#77]
Hello 
If I tried DQN with 

```
from stable_baselines3 import DQN
env = pong_v1.parallel_env(full_action_space=False)
env = ss.color_reduction_v0(env, mode='full')
env = ss.resize_v0(env, x_size=64m y_size=64)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 1, num_cpus=4, base_class='stable_baselines3')
model = DQN('CnnPolicy', env, verbose=1)
```

It says that 
`ValueError: Error: the model does not support multiple envs; it requires a single vectorized environment.`

I am wondering it pettingzoo has a single vectorized environment?

**Comment by justinkterry** [comment]
Making this work would require a different wrapper (which wouldn't be too hard for you to do if you wanted) or adding new functionality to supersuit.

The way `ss.pettingzoo_env_to_vec_env_v0(env)` works is that it tricks each agent of the environment into a "seperate environment" in the vectorized code. However, in SB3 DQNs don't have vector env support. This means you'd either have to add vec env support to DQNs in SB3, fork SB3 to hack a solution to this, or create a supersuit wrapper that functions as a single agent but alternates which agent can be acted on. You could also use the autonomous learning library, which should support what you want to do out of the box and has full rainbow DQN features.

**Comment by Ann-eat-apple** [comment]
@justinkterry , Thanks for your quick reply. Is there sample code for running the "autonomous learning library" with supersuit?

**Comment by justinkterry** [comment]
@weepingwillowben you have some somewhere right?

**Comment by weepingwillowben** [comment]
I do, but ALL's support is definitely not "out of box". The DQN agents are not parallel agents, so the vector environment hack doesn't work. Here is the code I used to train the atari environments with parameter shared Rainbow DQN.

https://gist.github.com/weepingwillowben/cbf4c0a674ad24d0e095263a0b553726

**Comment by justinkterry** [comment]
Let us know if you need anything else
