### ISSUE TITLE
Supersuit wrappers override underlying env behavior?

### ISSUE THREAD

**Issue by jbuckman** [PettingZoo-Team/SuperSuit#82]
Hi, I'm trying to replicate the classic Atari setup using SuperSuit. One thing I want to check is whether SuperSuit overrides the settings built into the gym envs, and to what extent. Here's some code:

```        env = gym.make("SpaceInvaders-v0")
        env = supersuit.max_observation_v0(env, 2)
        env = supersuit.sticky_actions_v0(env, repeat_action_probability=0.25)
        env = supersuit.frame_skip_v0(env, (2,5))
        env = supersuit.color_reduction_v0(env, 'full')
        env = supersuit.resize_v0(env, (84,84))
        env = supersuit.frame_stack_v1(env, 4)
```

So, my concern is that `env = gym.make("SpaceInvaders-v0")` comes with some baggage, and some functionality is duplicated. For example, I believe that SpaceInvaders-v0 already has frameskip (2, 5), and also sticky_actions 0.25. Will the current code double down on those things?

There's also the timelimit, which I know can be removed by using `env = gym.make("SpaceInvaders-v0").env`. Is that overriden by SuperSuit by default, or is that kept?

**Comment by justinkterry** [comment]
You need to use gym.make("SpaceInvadersNoFrameskip-v4"), and it will work they way you want it. The time limit is not overridden by supersuit.

**Comment by jbuckman** [comment]
Perfect, thanks.
